"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
Do Not Move on to the next function until its tests report 'ok' or your code
may not work as expected.
"""

import unittest

from test_createNotebook import TestCreateNotebook
from test_milesPerGallon import TestMilesPerGallon
from test_recordTrip import TestRecordTrip
from test_listTrips import TestListTrips
from test_calculateMPG import TestCalculateMPG
from test_formatMenu import TestFormatMenu
from test_formatMenuPrompt import TestFormatMenuPrompt
from test_getUserString import TestGetUserString
from test_getUserFloat import TestGetUserFloat
from test_getDate import TestGetDate
from test_getMiles import TestGetMiles
from test_getGallons import TestGetGallons
from test_recordTripAction import TestRecordTripAction
from test_listTripsAction import TestListTripsAction
from test_calculateMPGAction import TestCalculateMPGAction
from test_quitAction import TestQuitAction
from test_applyAction import TestApplyAction
from test_saveNotebook import TestSaveNotebook

if __name__ == "__main__":
    testCases = [
        TestCreateNotebook,
        TestMilesPerGallon,
        TestRecordTrip,
        TestListTrips,
        TestCalculateMPG,
        TestFormatMenu,
        TestFormatMenuPrompt,
        TestGetUserString,
        TestGetUserFloat,
        TestGetDate,
        TestGetMiles,
        TestGetGallons,
        TestRecordTripAction,
        TestListTripsAction,
        TestCalculateMPGAction,
        TestQuitAction,
        TestApplyAction,
    ]

    allTests = []
    for testCase in testCases:
        allTests.append(unittest.TestLoader().loadTestsFromTestCase(testCase))

    unittest.TextTestRunner().run(unittest.TestSuite(allTests))
